name:  Docker Image CI
on: 
  workflow_dispatch:  

jobs: 
  build: 
    runs-on:  ubuntu-latest

    env: 
        SECRET_KEY: "supersecretkey"
        ALGORITHM: "HS256"
        HOST : "None.com"
        PORT : "8000"
        DB : "None"
        PASSWORD : "None"
        USER: "None"
        POSTGRES_DB: postgres_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pass
        POSTGRES_PORT: 5432

    steps: 
      - uses:  actions/checkout@v4

      # Construcción de la imagen con un nombre fijo
      - name:  Build the Docker image
        run:  docker build . --file Dockerfile --tag my-image-name: latest